### ISSUE TITLE
Instruction Details

### ISSUE THREAD

**Issue by VirusPilot** [ThunderMikey/rtl8812au-aircrack-dkms-aarch64#1]
Mikey,
I just arrived probably at the same situation (Pi4 with aarch64) where you started this repo. Not being the most experienced programmer, I just modified the original aircrack repo according to your changes but still no success (WiFi only works after a ifdown/ifup cycle but not after boot).
Maybe there is more in your repo so could you provide more instructions on how to implement your files? Any other idea?

**Comment by ThunderMikey** [comment]
Hi Pilot, I made this repo for Arch Linux. It uses the [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) in the [Arch Build System](https://wiki.archlinux.org/title/Arch_Build_System).

So if you are using Arch Linux, you can do the following:
```
makepkg -si
```

**Comment by VirusPilot** [comment]
Ah, I am using raspios-buster-arm64, did you ever try this? Any idea why it won't work with buster?

**Comment by ThunderMikey** [comment]
Sorry, I don't have buster installed. I have only verified my patch when applying the diff to commit
https://github.com/ThunderMikey/rtl8812au-aircrack-dkms-aarch64/blob/f38d19ca4f40d167bbc49c7127fa6e154de4e09d/PKGBUILD#L6

So make sure you checkout the commit before applying the patch.

**Comment by VirusPilot** [comment]
Will do.

**Comment by VirusPilot** [comment]
No success either, I am afraid I have to either switch to 32bit buster or drop using the rtl8812 ...
